echo off
taskkill /f /T /IM kHome.Exe 
taskkill /f /T /IM Ultimaker-Cura.exe
taskkill /f /T /IM horizon_client_service.exe
taskkill /f /T /IM synergyd.exe 
taskkill /f /T /IM HMSCoreService.exe
taskkill /f /T /IM ftscanmgrhv.exe 
taskkill /f /T /IM BasicService.exe 
taskkill /f /T /IM SyncService.exe 
taskkill /f /T /IM EPWD.exe
taskkill /f /T /IM service_update.exe 
taskkill /f /T /IM TracSrvWrapper.exe
taskkill /f /T /IM vmware-usbarbitrator64.exe
taskkill /f /T /IM hasplmv.exe
taskkill /f /T /IM QHWatchdog.exe 
taskkill /f /T /IM HwMdcCenter.exe
taskkill /f /T /IM Telegram.exe
taskkill /f /T /IM browser.exe
taskkill /f /T /IM TrGUI.exe
taskkill /f /T /IM vmware-view.exe
taskkill /f /T /IM scalc.exe
taskkill /f /T /IM soffice.exe
taskkill /f /T /IM Teams.exe
taskkill /f /T /IM HUAWEI Cloud.exe
taskkill /f /T /IM msedge.exe
taskkill /f /T /IM Cortana.exe
taskkill /f /T /IM Lightshot.exe
taskkill /f /T /IM GameBar.exe
taskkill /f /T /IM GameBarFTServer.exe
taskkill /f /T /IM TracCAPI.exe
taskkill /f /T /IM vmware-remotemks.exe
taskkill /f /T /IM HxOutlook.exe
taskkill /f /T /IM HxTsr.exe
taskkill /f /T /IM HxAccounts.exe
taskkill /f /T /IM synergys.exe
taskkill /f /T /IM synergyd.exe
taskkill /f /T /IM soffice.bin
taskkill /f /T /IM code.exe
taskkill /f /T /IM cmd.exe
taskkill /f /T /IM TrueConf.exe
taskkill /f /T /IM YandexDisk2.exe
taskkill /f /T /IM vlc.exe
taskkill /f /T /IM Postman.exe
taskkill /f /T /IM Zoom.exe
taskkill /f /T /IM msedgewebview2.exe
taskkill /f /T /IM zWebview2Agent.exe
taskkill /f /T /IM bdcam.exe
taskkill /f /T /IM EPWD.exe
taskkill /f /T /IM EPWD_Tool.exe
taskkill /f /T /IM DFSSearchService.exe
taskkill /f /T /IM GoogleCrashHandler.exe
taskkill /f /T /IM GoogleCrashHandler64.exe
taskkill /f /T /IM hasplms.exe
taskkill /f /T /IM HiviewService.exe
taskkill /f /T /IM HMSCoreService.exe
taskkill /f /T /IM horizon_client_service.exe
taskkill /f /T /IM msteams.exe
taskkill /f /T /IM OfficeClickToRun.exe
taskkill /f /T /IM osdservice.exe
taskkill /f /T /IM service_update.exe
taskkill /f /T /IM service_update.exe
taskkill /f /T /IM vpnui.exe
taskkill /f /T /IM TracSrvWrapper.exe